### ISSUE TITLE
Error: Can't find variable: self

### ISSUE THREAD

**Issue by Connorelsea** [matthew-andrews/isomorphic-fetch#125]
Hello.

I am using `redux-api-middleware` which is using version 2.2.1 of `isomorphic-fetch`. I am experiencing an error where `self` is undefined in React Native, which is a problem with this version of `isomorphic-fetch`. Most issues I have seen regarding this issue have been closed, but I feel that this is a fairly common issue and I have not been able to find a good solution. I'd love to work together, with a maintainer or anyone else having this problem, to solve it.

Thank you for reading and for your work on this library.

The error seems to be coming from this file:

![image](https://cloud.githubusercontent.com/assets/1844458/23625510/07b163ca-026f-11e7-84a4-e263df725ef7.png)

Here is the stack trace:

![image](https://cloud.githubusercontent.com/assets/1844458/23625408/af3cebec-026e-11e7-87a4-2dca3b15b93a.png)

**Comment by karimmortabit** [comment]
Here is a fix I use :
```javascript
require('whatwg-fetch');
// module.exports = self.fetch.bind(self);
var globalObject = typeof self === "undefined" ? global : self;
module.exports = globalObject.fetch.bind(globalObject);

```

**Comment by gardner** [comment]
A place to start: https://github.com/apollographql/apollo-client/compare/6bd8786f88d575b0f45a27a02ccc9ce8ceb38ab2...aae04f76913769836308b1eb87ecab6e0efc4784

**Comment by CaryLandholt** [comment]
This worked for me (https://github.com/apollographql/apollo-link/issues/75#issuecomment-333328069)

**Comment by lquixada** [comment]
Hi guys! I work in a project that the same javascript codebase needs to run on different platforms (browsers, node and react native). Because of this issue, I had a hard time to find a replacement. Since this lib is outdated and no longer maintained, [cross-fetch](https://github.com/lquixada/cross-fetch) was created to fill this gap. It has the same shape of isomorphic-fetch but updated and fixed. Also polyfill is an optional thing. Hope it's useful for you as it is for me.

**Comment by EugenePizzerbert** [comment]
npm add whatwg-fetch@2.0.4 --save
