### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ckeeney** [matthew-andrews/isomorphic-fetch#133]
This project still has activity.  I see @matthew-andrews commenting as recently as 8 days ago.  However, the master branch has not been touched in nearly a year.  

The [releases page](https://github.com/matthew-andrews/isomorphic-fetch/releases) shows the most recent release, v2.1.1, was published nearly 2 years ago.  npmjs.com shows the most recent release of [2.2.1 a year ago](https://www.npmjs.com/package/isomorphic-fetch).

Additionally, there are 8 open pull requests, and many have been opened for a year or almost 2.

I'm not trying to beat up @matthew-andrews and appreciate the work that has gone into this project.  I just am wary about including something in my projects without understanding the current state of the project.

I suggest at the very least cleaning up the PRs.  Close out old ones that will never be merged, and deal with the ones that are left either with discussion or merging them in.

**Comment by fesebuv** [comment]
@matthew-andrews do you need help maintaining this project? Is there any way we can help? 
Thanks,
@fesebuv

**Comment by matthew-andrews** [comment]
Hi folks … sorry for the slow reply.

The project was always maintained to the point of being usable for the projects of which I was responsible.

There was a time when all the issues on this project seemed to be “fix this in order to allow react native to work”. I thought and still think react native is not a good direction for the web and didn't want to proactively support it. This was my small protest.

I was kindly prompted to have a look at this project again by someone emailing me about a minor security issue in a dependency it was bringing in yesterday. Now since I have a bit more time, I have been tidying it up a little.

I would encourage people to test their projects against the `master` branch of this repo to make sure nothing has broken. I will release it as a major version soon.
