### ISSUE TITLE
Should input without schema be default to https?

### ISSUE THREAD

**Issue by bitinn** [matthew-andrews/isomorphic-fetch#14]
I mean this line:

https://github.com/matthew-andrews/isomorphic-fetch/blob/master/server.js#L6

While it's *safer*, it's probably not what browser would do (I mean if you type example.com, it would default to http, at least currently they are.)

I struggle with this decision when writing node-fetch (there are no origin to speak of), and decide user should just normalize the url the way they prefer instead.

**Comment by matthew-andrews** [comment]
hmm. You're right but it probably doesn't matter too much. If you're using `//example.com` style URLs then you have to make sure the URL you're loading will work on https anyway.  I choose https because I wanted to encourage https :-).  But your notes about the browser are probably right.

**Comment by matthew-andrews** [comment]
Thinking about this more I think if you're using `//example.com` schema you *probably* know that endpoint supports https (otherwise you'd use http explicitly) so we might as well use it.

I think this a reasonable case where we don't have to try to match browser behaviour (which is probably the way it is for legacy reasons) and do something better — ie. put security first.
