### ISSUE TITLE
Workaround for React Native

### ISSUE THREAD

**Issue by kenfehling** [matthew-andrews/isomorphic-fetch#23]
Hi, I'm using  `isomorphic-fetch` in a shared library used by React and React Native. React Native provides its own fetch, so I'm currently using a workaround adapted from [github/fetch#125](https://github.com/github/fetch/issues/125#issuecomment-94266403).

    if (typeof process !== 'undefined') {
        require('isomorphic-fetch');
    }
Just wondering if something like this should be integrated into the `isomorphic-fetch` library. Thanks.

**Comment by matthew-andrews** [comment]
Thank you for your suggestion.  I think your workaround seems neat enough for what is I imagine to be a fairly obscure use case so I would prefer not to put it into this library if possible.  Sorry!

**Comment by thessem** [comment]
@matthew-andrews would it be possible to take another look at this? I'm on react native and I'm using some libraries that pull in this one as a dependancy, I've had to shrinkwrap them so that they use https://github.com/matthew-andrews/isomorphic-fetch/pull/80 instead.

I understand it's unfair to expect you to support other people using your library badly, so I have no real expectations here, I just wanted to point out that perhaps the use case is slightly less obscure than you thought.

**Comment by julienvincent** [comment]
> I understand it's unfair to expect you to support other people using your library badly

It's not so much the case of people using the library badly, but rather people being unaware that fetch will break react-native.

I think that this is an issue that should be fixed/handled here as the alternative is filing PR's for every library that depends on fetch in order to use within react-native.

**Comment by sosaucily** [comment]
@kenfehling I'm in the same boat, trying to use Redux-API-middlware with reactNative.  

Can you elaborate a bit on how you were able to work around the problem?  My app blows up when importing from redux-api-middleware.  Thx

**Comment by thessem** [comment]
@sosaucily Shrinkwrap the dependancy... read up on shrinkwrapping in npm, but the short version is you change the dependancy of redux-api-middleware in its package.json to point to https://github.com/matthew-andrews/isomorphic-fetch/pull/80 instead of this npm package (read up on using github branches as dependancies if you're not sure of the syntax), run `npm install` then `npm shrinkwrap` to make sure it sticks.

**Comment by wolframkriesing** [comment]
How I solved it (one of thousand solutions to this):
Problem was: a package I installed imported two node.js modules, one was `import url from 'url';` the other was `querystring` and the third was `isomorphic-fetch`. The error message didn't really point me to those in the beginning.
I am now in the process of removing/replacing those dependencies.
