### ISSUE TITLE
Suggestion: register.js

### ISSUE THREAD

**Issue by callumlocke** [matthew-andrews/isomorphic-fetch#86]
Apologies if this has been discussed before...

If I'm writing a library that uses isomorphic-fetch internally, I want a way to import it for local use inside my library only, without global side effects that might confuse my users.

I like the convention of using `import 'foo/register'` for global side-effects (installing/polyfilling/whatever), while `import foo from 'foo'` would just gets you a local import without any global side effects. This gives people the choice not to create a global. It also makes it more explicit (I was surprised to learn that `import fetch from 'isomorphic-fetch` would create a global *and* export me a local variable, as it means the `fetch from` bit is redundant).

Would you be up for updating isomorphic-fetch to work like this? (Would need a major version bump, obviously.)

[loud-rejection](https://github.com/sindresorhus/loud-rejection#register-script) and [coffeescript](https://github.com/jashkenas/coffeescript/blob/master/register.js) use this convention, and I think there are a few others.

**Comment by AlicanC** [comment]
Don't use this in a library.

If you are writing a library for browsers then leave the polyfilling to the user, just like this library leaves the polyfilling of `Promise` to you.

If you are writing a Node.js library then use [node-fetch](https://github.com/bitinn/node-fetch) since [the side effect is the whole point of this library](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js).

**Comment by callumlocke** [comment]
Yep I didn't know this lib just exports node-fetch, thanks
