### ISSUE TITLE
How does this differ from https://github.com/github/fetch

### ISSUE THREAD

**Issue by fourcolors** [matthew-andrews/isomorphic-fetch#92]
Didn't know where to ask questions, sorry if this isn't the right place. I can update the README if I know what the difference is, I just am trying to figure out what isomorphic-fetch adds vs just using the other fetch

Thanks!

**Comment by matthew-andrews** [comment]
Not very much!  There are two main fetch polyfills, one for the client [(GitHub's)](https://github.com/github/fetch) and one for the server [(Bitinn's)](https://github.com/bitinn/node-fetch/).  This library just pulls them both in so that you can `require('isomorphic-fetch')` on either the server or the client and it'll do something similar in both environments (make the `fetch` polyfill available globally).

If you only need to use fetch on just the client then this library won't do anything to help, it's only useful if you're writing JavaScript that will run on both the client and the server.
